import bcrypt from 'bcryptjs';

const data = {
  contents: [
    {
      name: 'Content Name',
      slug: 'sample-content1',
      image: '/images/default.png',
      category: 'Category1',
      cost: 'Free',
      hasCert: false,
      type: ['Type1', 'Type2'],
      description: 'sample description',
      url: 'http',
      rating: 4,
      numReviews: 0,
    },
    {
      name: 'Content Name',
      slug: 'sample-content2',
      image: '/images/default.png',
      category: 'Category1',
      cost: 'Free',
      hasCert: false,
      type: ['Type1', 'Type2'],
      description: 'sample description',
      url: 'http',
      rating: 4.5,
      numReviews: 0,
    },
    {
      name: 'Content Name',
      slug: 'sample-content3',
      image: '/images/default.png',
      category: 'Category1',
      cost: 'Paid',
      hasCert: true,
      type: ['Type1', 'Type2'],
      description: 'sample description',
      url: 'http',
      rating: 5,
      numReviews: 0,
    },
    {
      name: 'Content Name',
      slug: 'sample-content4',
      image: '/images/default.png',
      category: 'Category1',
      cost: 'Free',
      hasCert: false,
      type: ['Type1', 'Type2'],
      description: 'sample description',
      url: 'http',
      rating: 3,
      numReviews: 0,
    },
    {
      name: 'Content Name',
      slug: 'sample-content5',
      image: '/images/default.png',
      category: 'Category1',
      cost: 'Free',
      hasCert: false,
      type: ['Video Tutorial', 'Type2'],
      description: 'sample description',
      url: 'http',
      rating: 1,
      numReviews: 0,
    },
    // {
    //   name: 'Content Name',
    //   slug: 'sample-content6',
    //   image: '/images/default.png',
    //   category: 'Category1',
    //   cost: 'Free',
    //   hasCert: false,
    //   type: ['Type1', 'Type2'],
    //   description: 'sample description',
    //   url: 'http',
    //   rating: 0,
    //   numReviews: 0,
    // },
    // {
    //   name: 'Content Name',
    //   slug: 'sample-content7',
    //   image: '/images/default.png',
    //   category: 'Category1',
    //   cost: 'Free',
    //   hasCert: false,
    //   type: ['Type1', 'Type2'],
    //   description: 'sample description',
    //   url: 'http',
    //   rating: 0,
    //   numReviews: 0,
    // },
    // {
    //   name: 'Content Name',
    //   slug: 'sample-content8',
    //   image: '/images/default.png',
    //   category: 'Category1',
    //   cost: 'Free',
    //   hasCert: false,
    //   type: ['Type1', 'Type2'],
    //   description: 'sample description',
    //   url: 'http',
    //   rating: 0,
    //   numReviews: 0,
    // },
    // {
    //   name: 'Content Name',
    //   slug: 'sample-content9',
    //   image: '/images/default.png',
    //   category: 'Category1',
    //   cost: 'Free',
    //   hasCert: false,
    //   type: ['Type1', 'Type2'],
    //   description: 'sample description',
    //   url: 'http',
    //   rating: 0,
    //   numReviews: 0,
    // },
    // {
    //   name: 'Content Name',
    //   slug: 'sample-content10',
    //   image: '/images/default.png',
    //   category: 'Category1',
    //   cost: 'Free',
    //   hasCert: false,
    //   type: ['Type1', 'Type2'],
    //   description: 'sample description',
    //   url: 'http',
    //   rating: 0,
    //   numReviews: 0,
    // },
    // {
    //   name: 'Content Name',
    //   slug: 'sample-content11',
    //   image: '/images/default.png',
    //   category: 'Category1',
    //   cost: 'Free',
    //   hasCert: false,
    //   type: ['Type1', 'Type2'],
    //   description: 'sample description',
    //   url: 'http',
    //   rating: 0,
    //   numReviews: 0,
    // },
    // {
    //   name: 'Content Name',
    //   slug: 'sample-content12',
    //   image: '/images/default.png',
    //   category: 'Category1',
    //   cost: 'Free',
    //   hasCert: false,
    //   type: ['Type1', 'Type2'],
    //   description: 'sample description',
    //   url: 'http',
    //   rating: 0,
    //   numReviews: 0,
    // },
    // {
    //   name: 'Content Name',
    //   slug: 'sample-content13',
    //   image: '/images/default.png',
    //   category: 'Category1',
    //   cost: 'Free',
    //   hasCert: false,
    //   type: ['Type1', 'Type2'],
    //   description: 'sample description',
    //   url: 'http',
    //   rating: 0,
    //   numReviews: 0,
    // },
    {
      name: 'The Odin Project',
      slug: 'the-odin-project',
      image: '/images/theodinproject.png',
      category: 'Web Development',
      cost: 'Paid',
      hasCert: true,
      type: ['Text-Based', 'Hands On Project'],
      description: 'a web development course',
      url: 'https://www.theodinproject.com/',
      rating: 3,
      numReviews: 0,
    },
  ],

  users: [
    {
      name: 'Amirul',
      email: 'amirul@gmail.com',
      password: bcrypt.hashSync('123'),
      isAdmin: true,
    },
    {
      name: 'James',
      email: 'james@gmail.com',
      password: bcrypt.hashSync('123'),
      isAdmin: false,
    },
    {
      name: 'Rex',
      email: 'rex@gmail.com',
      password: bcrypt.hashSync('123'),
    },
  ],
};

export default data;
